
INSERT INTO thermocheck.contractor_akademie_quiz (modul_id, frage, antworten, reihenfolge) VALUES
-- Modul 1: Grundlagen
('5b2946aa-07c4-4820-8d21-f906ac29954b', 'Was passiert, wenn ein U-Wert bei der Datenaufnahme falsch geschätzt wird?', '[{"text":"Das Angebot wird günstiger für den Kunden","korrekt":false},{"text":"Die Wärmepumpe wird falsch dimensioniert und verschleißt vorzeitig","korrekt":true},{"text":"Der Innendienst korrigiert das automatisch","korrekt":false},{"text":"Es hat keinen Einfluss, da die Software U-Werte selbst berechnet","korrekt":false}]'::jsonb, 1),
('5b2946aa-07c4-4820-8d21-f906ac29954b', 'Wie lange investiert das Ingenieurteam in die Berechnung pro Projekt?', '[{"text":"2 Stunden","korrekt":false},{"text":"6 Stunden","korrekt":false},{"text":"12 Stunden","korrekt":true},{"text":"24 Stunden","korrekt":false}]'::jsonb, 2),
('5b2946aa-07c4-4820-8d21-f906ac29954b', 'Was bedeutet das „Cinderella-Prinzip" im Kontext des Thermochecks?', '[{"text":"Jedes Haus bekommt die gleiche Standard-Wärmepumpe","korrekt":false},{"text":"Jedes Haus ist ein Unikat und braucht eine perfekt passende Lösung","korrekt":true},{"text":"Die Datenaufnahme muss vor Mitternacht abgeschlossen sein","korrekt":false},{"text":"Es gibt nur eine richtige Wärmepumpe pro Hersteller","korrekt":false}]'::jsonb, 3),
-- Modul 2: Service-Professionalität
('ccf4df14-0c28-4364-95d1-ae9c53d901ed', 'Ein Kunde fragt: „Was wird das ungefähr kosten?" – Welche Antwort ist korrekt?', '[{"text":"Rechnen Sie mit ca. 25.000 bis 35.000 Euro","korrekt":false},{"text":"Das ist ein normales Projekt, circa 30.000 Euro","korrekt":false},{"text":"Jedes Haus ist ein Unikat. Sie erhalten zeitnah ein maßgeschneidertes Angebot.","korrekt":true},{"text":"Das kann ich Ihnen erst nach der Berechnung sagen, aber grob 20.000 Euro","korrekt":false}]'::jsonb, 4),
('ccf4df14-0c28-4364-95d1-ae9c53d901ed', 'Wann müssen die Firmen-Hausschlappen gewechselt werden?', '[{"text":"Nur beim Betreten des Hauses","korrekt":false},{"text":"Beim Wechsel zwischen Innen- und Außenbereich","korrekt":true},{"text":"Nur wenn der Kunde es verlangt","korrekt":false},{"text":"Hausschlappen sind optional bei kurzen Terminen","korrekt":false}]'::jsonb, 5),
('ccf4df14-0c28-4364-95d1-ae9c53d901ed', 'Was ist die korrekte Vorstellung an der Haustür?', '[{"text":"Hallo, ich bin von der Heizungsfirma","korrekt":false},{"text":"Guten Tag, mein Name ist [Name]. Ich bin der Techniker von Galvanek für Ihren heutigen Termin.","korrekt":true},{"text":"Hi, ich mach den Thermocheck","korrekt":false},{"text":"Guten Tag, ich bin für die Wärmepumpe da","korrekt":false}]'::jsonb, 6),
-- Modul 3: Sicherheit
('b178db2b-9326-4b3f-8102-158f734d6964', 'Ihr entdeckt im Heizungsraum starken Schimmelbefall. Was tut ihr?', '[{"text":"Fenster öffnen und weiterarbeiten","korrekt":false},{"text":"Raum sofort verlassen, zum Auto gehen, Projektleitung anrufen","korrekt":true},{"text":"Den Kunden bitten, den Schimmel zu entfernen","korrekt":false},{"text":"Den Bereich mit Mundschutz betreten und schnell fotografieren","korrekt":false}]'::jsonb, 7),
('b178db2b-9326-4b3f-8102-158f734d6964', 'Wie früh müsst ihr einen Termin absagen, wenn ihr krank seid?', '[{"text":"Am gleichen Morgen reicht aus","korrekt":false},{"text":"12 Stunden vorher","korrekt":false},{"text":"Mindestens 24 Stunden vorher","korrekt":true},{"text":"48 Stunden vorher","korrekt":false}]'::jsonb, 8),
('b178db2b-9326-4b3f-8102-158f734d6964', 'Bevor ihr den Kunden fotografiert oder scannt – was ist Pflicht?', '[{"text":"Nichts, das ist im Vertrag geregelt","korrekt":false},{"text":"Die mündliche Einwilligung des Kunden aktiv einholen","korrekt":true},{"text":"Eine schriftliche Genehmigung unterschreiben lassen","korrekt":false},{"text":"Den Datenschutzbeauftragten informieren","korrekt":false}]'::jsonb, 9),
-- Modul 4: Terminvorbereitung
('01448ab8-9a0e-426a-839f-7e9bdaa4ccfb', 'Warum dürft ihr die Fahrzeit NICHT am Vorabend mit Google Maps planen?', '[{"text":"Google Maps funktioniert abends nicht richtig","korrekt":false},{"text":"Die Verkehrsdaten basieren auf der aktuellen (leeren) Verkehrslage, nicht auf der Rush Hour am nächsten Tag","korrekt":true},{"text":"Es ist Firmenvorschrift, nur morgens zu planen","korrekt":false},{"text":"Die Route ändert sich über Nacht durch Baustellen","korrekt":false}]'::jsonb, 10),
('01448ab8-9a0e-426a-839f-7e9bdaa4ccfb', 'Wie berechnet ihr die korrekte Abfahrtszeit mit der Puffer-Regel?', '[{"text":"Kürzeste Google-Zeit minus 15 Minuten","korrekt":false},{"text":"Längste Google-Zeit plus 1 Stunde","korrekt":false},{"text":"Mittelwert der Google-Zeitspanne plus 30 Minuten Puffer","korrekt":true},{"text":"Google-Zeit verdoppeln","korrekt":false}]'::jsonb, 11),
-- Modul 5: Ablauf vor Ort (Multiple Choice)
('e04f5fef-dda8-4b95-87c5-bf8941c90b44', 'Welche der folgenden Daten sind „Minimum Viable Data" – ohne sie kann kein Angebot erstellt werden? (Mehrere Antworten möglich)', '[{"text":"Vollständige Gebäudedaten und U-Werte","korrekt":true},{"text":"Farbfotos der Gartengestaltung","korrekt":false},{"text":"Jeder einzelne Heizkörper mit Typ, Maßen und Foto","korrekt":true},{"text":"Zählerschrank-Fotos offen und geschlossen","korrekt":true}]'::jsonb, 12),
-- Modul 6: Datenerhebung
('a4cb8918-c503-4b7d-8c0c-84daca3aac65', 'Was ist die „Master-Foto-Regel" für den Zählerschrank?', '[{"text":"Ein Foto des Typenschilds genügt","korrekt":false},{"text":"Komplettes, frontales Foto des gesamten Zählerschranks bei geöffneter Tür","korrekt":true},{"text":"Drei Fotos aus verschiedenen Winkeln","korrekt":false},{"text":"Nur die Sicherungen müssen einzeln fotografiert werden","korrekt":false}]'::jsonb, 13),
('a4cb8918-c503-4b7d-8c0c-84daca3aac65', 'Vor dem Absenden des Datensatzes – welche vier Fragen müsst ihr prüfen?', '[{"text":"Heizkörper-Maße plausibel, Fotos scharf, Zählerschrank vollständig, Einbringmaße dokumentiert","korrekt":true},{"text":"Kunden-Unterschrift, Termin-Dauer, Fahrtkosten, Materialliste","korrekt":false},{"text":"U-Werte, Heizlast, Wärmepumpentyp, Preis","korrekt":false},{"text":"Scan-Qualität, Wetterdaten, Nachbargebäude, Grundstückgröße","korrekt":false}]'::jsonb, 14),
('a4cb8918-c503-4b7d-8c0c-84daca3aac65', 'Ein 20 cm breiter Heizkörper in einem 30 qm Wohnzimmer – was bedeutet das?', '[{"text":"Das ist ein moderner Kompaktheizkörper","korrekt":false},{"text":"Das kann nicht stimmen – Maße sind falsch oder ein Heizkörper wurde übersehen","korrekt":true},{"text":"Der Raum hat zusätzlich Fußbodenheizung","korrekt":false},{"text":"Ist normal bei gut gedämmten Häusern","korrekt":false}]'::jsonb, 15),
('a4cb8918-c503-4b7d-8c0c-84daca3aac65', 'U-Werte von 0,4 bis 0,6 bedeuten...', '[{"text":"Sehr schlechte Dämmung","korrekt":false},{"text":"Durchschnittliche Dämmung","korrekt":false},{"text":"Relativ gute Dämmung","korrekt":true},{"text":"Keine Dämmung vorhanden","korrekt":false}]'::jsonb, 16),
('a4cb8918-c503-4b7d-8c0c-84daca3aac65', 'Nachträgliche Dämmung wird in der Software eingetragen...', '[{"text":"Global für das gesamte Gebäude","korrekt":false},{"text":"Pro Etage","korrekt":false},{"text":"Pro Raum","korrekt":true},{"text":"Pro Bauteil-Typ","korrekt":false}]'::jsonb, 17),
('a4cb8918-c503-4b7d-8c0c-84daca3aac65', 'Warum müssen Heizkreise (Heizkörper vs. Fußbodenheizung) manuell getrennt werden?', '[{"text":"Aus optischen Gründen im Report","korrekt":false},{"text":"Wegen unterschiedlicher Vorlauftemperaturen und korrekter Darstellung im 4DZ-Formular","korrekt":true},{"text":"Die Software erlaubt nur einen Heizkörpertyp pro Heizkreis","korrekt":false},{"text":"Das ist nur bei Gebäuden vor 1990 nötig","korrekt":false}]'::jsonb, 18),
('a4cb8918-c503-4b7d-8c0c-84daca3aac65', 'Im 3D-Scan-Modell: Welche Farbe hat eine Außenwand?', '[{"text":"Grau","korrekt":false},{"text":"Blau","korrekt":true},{"text":"Gelb","korrekt":false},{"text":"Rot","korrekt":false}]'::jsonb, 19),
('a4cb8918-c503-4b7d-8c0c-84daca3aac65', 'Eine Balkontür wird im 3D-Modell als Tür erkannt. Was müsst ihr tun?', '[{"text":"Nichts, das ist korrekt","korrekt":false},{"text":"Sie als Fenster behandeln und den Außenwand-Wert verwenden","korrekt":true},{"text":"Den U-Wert auf 2,9 setzen (Außentür-Wert)","korrekt":false},{"text":"Die Tür aus dem Modell löschen","korrekt":false}]'::jsonb, 20),
-- Modul 7: Tool-Workflow
('bc2fc0a2-cf7b-415e-a759-9a5136f6a649', 'Innerhalb welcher Frist muss das Zoho-Formular nach dem ThermoCheck abgeschickt werden?', '[{"text":"12 Stunden","korrekt":false},{"text":"24 Stunden","korrekt":false},{"text":"36 Stunden","korrekt":true},{"text":"72 Stunden","korrekt":false}]'::jsonb, 21),
('bc2fc0a2-cf7b-415e-a759-9a5136f6a649', 'Wie viele Unterschriften müsst ihr vom Kunden vor Ort holen?', '[{"text":"Eine (Anwesenheit)","korrekt":false},{"text":"Zwei: Aufstellort und Anwesenheit","korrekt":true},{"text":"Drei: Datenschutz, Aufstellort und Anwesenheit","korrekt":false},{"text":"Keine, das läuft digital","korrekt":false}]'::jsonb, 22),
('bc2fc0a2-cf7b-415e-a759-9a5136f6a649', 'Der Kunde hat KEINE PV-Anlage und will auch keine. Wie geht ihr im Zoho-Formular vor?', '[{"text":"Nein anklicken und das PV-Formular überspringen","korrekt":false},{"text":"Ja anklicken und ein Bild mit dem Vermerk Kundin will keine PV einfügen","korrekt":true},{"text":"Das Feld leer lassen","korrekt":false},{"text":"Die Projektleitung informieren","korrekt":false}]'::jsonb, 23),
('bc2fc0a2-cf7b-415e-a759-9a5136f6a649', 'Wie fotografiert ihr den Heizungsraum richtig?', '[{"text":"An einem Punkt stehen und im Kreis fotografieren","korrekt":false},{"text":"Von einer Ecke zur gegenüberliegenden Ecke fotografieren","korrekt":true},{"text":"Nur die Heizung selbst fotografieren","korrekt":false},{"text":"Ein Panoramafoto genügt","korrekt":false}]'::jsonb, 24),
-- Modul 8: Abschluss
('561e7f1f-e2b6-49ee-b512-49007679b24e', 'Ein Kunde fragt, welcher Wärmepumpentyp für sein Haus am besten ist. Was antwortet ihr?', '[{"text":"Eine Luft-Wasser-Wärmepumpe ist immer die beste Wahl","korrekt":false},{"text":"Ich nehme die Daten auf, unsere Ingenieure legen die optimale Lösung aus","korrekt":true},{"text":"Das kann ich Ihnen anhand der Gebäudedaten direkt sagen","korrekt":false},{"text":"Typ X ist für Ihr Haus perfekt","korrekt":false}]'::jsonb, 25),
('561e7f1f-e2b6-49ee-b512-49007679b24e', 'Welche vier Schritte nach dem Termin erklärt ihr dem Kunden?', '[{"text":"Rechnung, Bauantrag, Förderung, Installation","korrekt":false},{"text":"Datenübermittlung, Angebotserstellung, Angebotspräsentation, Förderservice","korrekt":true},{"text":"Scan-Upload, U-Wert-Berechnung, Heizlast-Check, Bestellung","korrekt":false},{"text":"Qualitätsprüfung, Zweitmeinung, Angebot, Baustart-Termin","korrekt":false}]'::jsonb, 26),
-- Modul 9: Sonderfälle
('473e603e-8b88-41f7-b5ae-188be7a89e79', 'Der Kunde ist nicht zu Hause. Was macht ihr zuerst?', '[{"text":"Sofort nach Hause fahren","korrekt":false},{"text":"Kalender checken, ob ihr bald wieder in der Nähe seid","korrekt":true},{"text":"Dem Kunden eine böse Nachricht schreiben","korrekt":false},{"text":"30 Minuten warten und dann gehen","korrekt":false}]'::jsonb, 27),
('473e603e-8b88-41f7-b5ae-188be7a89e79', 'Der Kunde behauptet, seine Wand sei gedämmt. Euer Klopftest zeigt Hohlraum. Was tut ihr?', '[{"text":"Dem Kunden erklären, dass er falsch liegt","korrekt":false},{"text":"Beides dokumentieren: Kundenangabe UND eigene Beobachtung","korrekt":true},{"text":"Nur die Kundenangabe verwenden","korrekt":false},{"text":"Den U-Wert auf gedämmt setzen, da der Kunde es besser weiß","korrekt":false}]'::jsonb, 28),
('473e603e-8b88-41f7-b5ae-188be7a89e79', 'Ein Kunde wird beleidigend. In welcher Reihenfolge handelt ihr?', '[{"text":"Zurückschimpfen, Termin abbrechen, Chef anrufen","korrekt":false},{"text":"Sachlich bleiben, Gespräch höflich abbrechen, zum Auto gehen, Projektleitung anrufen","korrekt":true},{"text":"Weiterarbeiten und es ignorieren","korrekt":false},{"text":"Den Kunden bitten, sich zu entschuldigen","korrekt":false}]'::jsonb, 29),
-- Modul 10: QA
('a77487cc-fb73-4233-b6d8-0c95c9ef1550', 'Was unterscheidet einen akzeptablen „Fehler" von „Schlampigkeit"?', '[{"text":"Fehler passieren nur Anfängern, Schlampigkeit nur Profis","korrekt":false},{"text":"Fehler passieren trotz Sorgfalt, Schlampigkeit ist mangelnder Anspruch trotz Feedback","korrekt":true},{"text":"Beides wird gleich behandelt","korrekt":false},{"text":"Fehler werden bestraft, Schlampigkeit nicht","korrekt":false}]'::jsonb, 30);
